before:
  hooks:
    - go mod download 
    - go mod verify
builds:
  - goos:
    - linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'