name: semantic release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopus-dev
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
          prerelease: true
          force-bump-patch-version: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
